// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: proto/steelbeam.proto

package steelbeam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SteelBeam message representing a steel beam with all its properties
type SteelBeam struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	SectionDesignation           string                 `protobuf:"bytes,1,opt,name=section_designation,json=sectionDesignation,proto3" json:"section_designation,omitempty"`
	MassPerMetre                 float64                `protobuf:"fixed64,2,opt,name=mass_per_metre,json=massPerMetre,proto3" json:"mass_per_metre,omitempty"`
	DepthOfSection               float64                `protobuf:"fixed64,3,opt,name=depth_of_section,json=depthOfSection,proto3" json:"depth_of_section,omitempty"`
	WidthOfSection               float64                `protobuf:"fixed64,4,opt,name=width_of_section,json=widthOfSection,proto3" json:"width_of_section,omitempty"`
	ThicknessWeb                 float64                `protobuf:"fixed64,5,opt,name=thickness_web,json=thicknessWeb,proto3" json:"thickness_web,omitempty"`
	ThicknessFlange              float64                `protobuf:"fixed64,6,opt,name=thickness_flange,json=thicknessFlange,proto3" json:"thickness_flange,omitempty"`
	RootRadius                   float64                `protobuf:"fixed64,7,opt,name=root_radius,json=rootRadius,proto3" json:"root_radius,omitempty"`
	DepthBetweenFillets          float64                `protobuf:"fixed64,8,opt,name=depth_between_fillets,json=depthBetweenFillets,proto3" json:"depth_between_fillets,omitempty"`
	RatiosForLocalBucklingWeb    float64                `protobuf:"fixed64,9,opt,name=ratios_for_local_buckling_web,json=ratiosForLocalBucklingWeb,proto3" json:"ratios_for_local_buckling_web,omitempty"`
	RatiosForLocalBucklingFlange float64                `protobuf:"fixed64,10,opt,name=ratios_for_local_buckling_flange,json=ratiosForLocalBucklingFlange,proto3" json:"ratios_for_local_buckling_flange,omitempty"`
	EndClearance                 float64                `protobuf:"fixed64,11,opt,name=end_clearance,json=endClearance,proto3" json:"end_clearance,omitempty"`
	Notch                        float64                `protobuf:"fixed64,12,opt,name=notch,proto3" json:"notch,omitempty"`
	DimensionsForDetailingN      float64                `protobuf:"fixed64,13,opt,name=dimensions_for_detailing_n,json=dimensionsForDetailingN,proto3" json:"dimensions_for_detailing_n,omitempty"`
	SurfaceAreaPerMetre          float64                `protobuf:"fixed64,14,opt,name=surface_area_per_metre,json=surfaceAreaPerMetre,proto3" json:"surface_area_per_metre,omitempty"`
	SurfaceAreaPerTonne          float64                `protobuf:"fixed64,15,opt,name=surface_area_per_tonne,json=surfaceAreaPerTonne,proto3" json:"surface_area_per_tonne,omitempty"`
	SecondMomentOfAreaAxisY      float64                `protobuf:"fixed64,16,opt,name=second_moment_of_area_axis_y,json=secondMomentOfAreaAxisY,proto3" json:"second_moment_of_area_axis_y,omitempty"`
	SecondMomentOfAreaAxisZ      float64                `protobuf:"fixed64,17,opt,name=second_moment_of_area_axis_z,json=secondMomentOfAreaAxisZ,proto3" json:"second_moment_of_area_axis_z,omitempty"`
	RadiusOfGyrationAxisY        float64                `protobuf:"fixed64,18,opt,name=radius_of_gyration_axis_y,json=radiusOfGyrationAxisY,proto3" json:"radius_of_gyration_axis_y,omitempty"`
	RadiusOfGyrationAxisZ        float64                `protobuf:"fixed64,19,opt,name=radius_of_gyration_axis_z,json=radiusOfGyrationAxisZ,proto3" json:"radius_of_gyration_axis_z,omitempty"`
	ElasticModulusAxisY          float64                `protobuf:"fixed64,20,opt,name=elastic_modulus_axis_y,json=elasticModulusAxisY,proto3" json:"elastic_modulus_axis_y,omitempty"`
	ElasticModulusAxisZ          float64                `protobuf:"fixed64,21,opt,name=elastic_modulus_axis_z,json=elasticModulusAxisZ,proto3" json:"elastic_modulus_axis_z,omitempty"`
	PlasticModulusAxisY          float64                `protobuf:"fixed64,22,opt,name=plastic_modulus_axis_y,json=plasticModulusAxisY,proto3" json:"plastic_modulus_axis_y,omitempty"`
	PlasticModulusAxisZ          float64                `protobuf:"fixed64,23,opt,name=plastic_modulus_axis_z,json=plasticModulusAxisZ,proto3" json:"plastic_modulus_axis_z,omitempty"`
	BucklingParameter            float64                `protobuf:"fixed64,24,opt,name=buckling_parameter,json=bucklingParameter,proto3" json:"buckling_parameter,omitempty"`
	TorsionalIndex               float64                `protobuf:"fixed64,25,opt,name=torsional_index,json=torsionalIndex,proto3" json:"torsional_index,omitempty"`
	WarpingConstant              float64                `protobuf:"fixed64,26,opt,name=warping_constant,json=warpingConstant,proto3" json:"warping_constant,omitempty"`
	TorsionalConstant            float64                `protobuf:"fixed64,27,opt,name=torsional_constant,json=torsionalConstant,proto3" json:"torsional_constant,omitempty"`
	AreaOfSection                float64                `protobuf:"fixed64,28,opt,name=area_of_section,json=areaOfSection,proto3" json:"area_of_section,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *SteelBeam) Reset() {
	*x = SteelBeam{}
	mi := &file_proto_steelbeam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SteelBeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SteelBeam) ProtoMessage() {}

func (x *SteelBeam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_steelbeam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SteelBeam.ProtoReflect.Descriptor instead.
func (*SteelBeam) Descriptor() ([]byte, []int) {
	return file_proto_steelbeam_proto_rawDescGZIP(), []int{0}
}

func (x *SteelBeam) GetSectionDesignation() string {
	if x != nil {
		return x.SectionDesignation
	}
	return ""
}

func (x *SteelBeam) GetMassPerMetre() float64 {
	if x != nil {
		return x.MassPerMetre
	}
	return 0
}

func (x *SteelBeam) GetDepthOfSection() float64 {
	if x != nil {
		return x.DepthOfSection
	}
	return 0
}

func (x *SteelBeam) GetWidthOfSection() float64 {
	if x != nil {
		return x.WidthOfSection
	}
	return 0
}

func (x *SteelBeam) GetThicknessWeb() float64 {
	if x != nil {
		return x.ThicknessWeb
	}
	return 0
}

func (x *SteelBeam) GetThicknessFlange() float64 {
	if x != nil {
		return x.ThicknessFlange
	}
	return 0
}

func (x *SteelBeam) GetRootRadius() float64 {
	if x != nil {
		return x.RootRadius
	}
	return 0
}

func (x *SteelBeam) GetDepthBetweenFillets() float64 {
	if x != nil {
		return x.DepthBetweenFillets
	}
	return 0
}

func (x *SteelBeam) GetRatiosForLocalBucklingWeb() float64 {
	if x != nil {
		return x.RatiosForLocalBucklingWeb
	}
	return 0
}

func (x *SteelBeam) GetRatiosForLocalBucklingFlange() float64 {
	if x != nil {
		return x.RatiosForLocalBucklingFlange
	}
	return 0
}

func (x *SteelBeam) GetEndClearance() float64 {
	if x != nil {
		return x.EndClearance
	}
	return 0
}

func (x *SteelBeam) GetNotch() float64 {
	if x != nil {
		return x.Notch
	}
	return 0
}

func (x *SteelBeam) GetDimensionsForDetailingN() float64 {
	if x != nil {
		return x.DimensionsForDetailingN
	}
	return 0
}

func (x *SteelBeam) GetSurfaceAreaPerMetre() float64 {
	if x != nil {
		return x.SurfaceAreaPerMetre
	}
	return 0
}

func (x *SteelBeam) GetSurfaceAreaPerTonne() float64 {
	if x != nil {
		return x.SurfaceAreaPerTonne
	}
	return 0
}

func (x *SteelBeam) GetSecondMomentOfAreaAxisY() float64 {
	if x != nil {
		return x.SecondMomentOfAreaAxisY
	}
	return 0
}

func (x *SteelBeam) GetSecondMomentOfAreaAxisZ() float64 {
	if x != nil {
		return x.SecondMomentOfAreaAxisZ
	}
	return 0
}

func (x *SteelBeam) GetRadiusOfGyrationAxisY() float64 {
	if x != nil {
		return x.RadiusOfGyrationAxisY
	}
	return 0
}

func (x *SteelBeam) GetRadiusOfGyrationAxisZ() float64 {
	if x != nil {
		return x.RadiusOfGyrationAxisZ
	}
	return 0
}

func (x *SteelBeam) GetElasticModulusAxisY() float64 {
	if x != nil {
		return x.ElasticModulusAxisY
	}
	return 0
}

func (x *SteelBeam) GetElasticModulusAxisZ() float64 {
	if x != nil {
		return x.ElasticModulusAxisZ
	}
	return 0
}

func (x *SteelBeam) GetPlasticModulusAxisY() float64 {
	if x != nil {
		return x.PlasticModulusAxisY
	}
	return 0
}

func (x *SteelBeam) GetPlasticModulusAxisZ() float64 {
	if x != nil {
		return x.PlasticModulusAxisZ
	}
	return 0
}

func (x *SteelBeam) GetBucklingParameter() float64 {
	if x != nil {
		return x.BucklingParameter
	}
	return 0
}

func (x *SteelBeam) GetTorsionalIndex() float64 {
	if x != nil {
		return x.TorsionalIndex
	}
	return 0
}

func (x *SteelBeam) GetWarpingConstant() float64 {
	if x != nil {
		return x.WarpingConstant
	}
	return 0
}

func (x *SteelBeam) GetTorsionalConstant() float64 {
	if x != nil {
		return x.TorsionalConstant
	}
	return 0
}

func (x *SteelBeam) GetAreaOfSection() float64 {
	if x != nil {
		return x.AreaOfSection
	}
	return 0
}

// Request message to get all beams
type GetBeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeamsRequest) Reset() {
	*x = GetBeamsRequest{}
	mi := &file_proto_steelbeam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeamsRequest) ProtoMessage() {}

func (x *GetBeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_steelbeam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeamsRequest.ProtoReflect.Descriptor instead.
func (*GetBeamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_steelbeam_proto_rawDescGZIP(), []int{1}
}

// Response message containing list of beams
type GetBeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beams         []*SteelBeam           `protobuf:"bytes,1,rep,name=beams,proto3" json:"beams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeamsResponse) Reset() {
	*x = GetBeamsResponse{}
	mi := &file_proto_steelbeam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeamsResponse) ProtoMessage() {}

func (x *GetBeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_steelbeam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeamsResponse.ProtoReflect.Descriptor instead.
func (*GetBeamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_steelbeam_proto_rawDescGZIP(), []int{2}
}

func (x *GetBeamsResponse) GetBeams() []*SteelBeam {
	if x != nil {
		return x.Beams
	}
	return nil
}

// Request message to get a specific beam by section designation
type GetBeamRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SectionDesignation string                 `protobuf:"bytes,1,opt,name=section_designation,json=sectionDesignation,proto3" json:"section_designation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetBeamRequest) Reset() {
	*x = GetBeamRequest{}
	mi := &file_proto_steelbeam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeamRequest) ProtoMessage() {}

func (x *GetBeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_steelbeam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeamRequest.ProtoReflect.Descriptor instead.
func (*GetBeamRequest) Descriptor() ([]byte, []int) {
	return file_proto_steelbeam_proto_rawDescGZIP(), []int{3}
}

func (x *GetBeamRequest) GetSectionDesignation() string {
	if x != nil {
		return x.SectionDesignation
	}
	return ""
}

// Response message containing a single beam
type GetBeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beam          *SteelBeam             `protobuf:"bytes,1,opt,name=beam,proto3" json:"beam,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeamResponse) Reset() {
	*x = GetBeamResponse{}
	mi := &file_proto_steelbeam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeamResponse) ProtoMessage() {}

func (x *GetBeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_steelbeam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeamResponse.ProtoReflect.Descriptor instead.
func (*GetBeamResponse) Descriptor() ([]byte, []int) {
	return file_proto_steelbeam_proto_rawDescGZIP(), []int{4}
}

func (x *GetBeamResponse) GetBeam() *SteelBeam {
	if x != nil {
		return x.Beam
	}
	return nil
}

func (x *GetBeamResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Request message to create a new beam
type CreateBeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beam          *SteelBeam             `protobuf:"bytes,1,opt,name=beam,proto3" json:"beam,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBeamRequest) Reset() {
	*x = CreateBeamRequest{}
	mi := &file_proto_steelbeam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeamRequest) ProtoMessage() {}

func (x *CreateBeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_steelbeam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeamRequest.ProtoReflect.Descriptor instead.
func (*CreateBeamRequest) Descriptor() ([]byte, []int) {
	return file_proto_steelbeam_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBeamRequest) GetBeam() *SteelBeam {
	if x != nil {
		return x.Beam
	}
	return nil
}

// Response message for beam creation
type CreateBeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beam          *SteelBeam             `protobuf:"bytes,1,opt,name=beam,proto3" json:"beam,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBeamResponse) Reset() {
	*x = CreateBeamResponse{}
	mi := &file_proto_steelbeam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeamResponse) ProtoMessage() {}

func (x *CreateBeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_steelbeam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeamResponse.ProtoReflect.Descriptor instead.
func (*CreateBeamResponse) Descriptor() ([]byte, []int) {
	return file_proto_steelbeam_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBeamResponse) GetBeam() *SteelBeam {
	if x != nil {
		return x.Beam
	}
	return nil
}

func (x *CreateBeamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBeamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for stock status
type GetStockStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Postcode      string                 `protobuf:"bytes,2,opt,name=postcode,proto3" json:"postcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockStatusRequest) Reset() {
	*x = GetStockStatusRequest{}
	mi := &file_proto_steelbeam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockStatusRequest) ProtoMessage() {}

func (x *GetStockStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_steelbeam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStockStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_steelbeam_proto_rawDescGZIP(), []int{7}
}

func (x *GetStockStatusRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetStockStatusRequest) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

// Response message for stock status
type GetStockStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Postcode      string                 `protobuf:"bytes,2,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockStatusResponse) Reset() {
	*x = GetStockStatusResponse{}
	mi := &file_proto_steelbeam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockStatusResponse) ProtoMessage() {}

func (x *GetStockStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_steelbeam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStockStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_steelbeam_proto_rawDescGZIP(), []int{8}
}

func (x *GetStockStatusResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetStockStatusResponse) GetPostcode() string {
	if x != nil {
		return x.Postcode
	}
	return ""
}

func (x *GetStockStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStockStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetStockStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_steelbeam_proto protoreflect.FileDescriptor

const file_proto_steelbeam_proto_rawDesc = "" +
	"\n" +
	"\x15proto/steelbeam.proto\x12\tsteelbeam\"\xe7\n" +
	"\n" +
	"\tSteelBeam\x12/\n" +
	"\x13section_designation\x18\x01 \x01(\tR\x12sectionDesignation\x12$\n" +
	"\x0emass_per_metre\x18\x02 \x01(\x01R\fmassPerMetre\x12(\n" +
	"\x10depth_of_section\x18\x03 \x01(\x01R\x0edepthOfSection\x12(\n" +
	"\x10width_of_section\x18\x04 \x01(\x01R\x0ewidthOfSection\x12#\n" +
	"\rthickness_web\x18\x05 \x01(\x01R\fthicknessWeb\x12)\n" +
	"\x10thickness_flange\x18\x06 \x01(\x01R\x0fthicknessFlange\x12\x1f\n" +
	"\vroot_radius\x18\a \x01(\x01R\n" +
	"rootRadius\x122\n" +
	"\x15depth_between_fillets\x18\b \x01(\x01R\x13depthBetweenFillets\x12@\n" +
	"\x1dratios_for_local_buckling_web\x18\t \x01(\x01R\x19ratiosForLocalBucklingWeb\x12F\n" +
	" ratios_for_local_buckling_flange\x18\n" +
	" \x01(\x01R\x1cratiosForLocalBucklingFlange\x12#\n" +
	"\rend_clearance\x18\v \x01(\x01R\fendClearance\x12\x14\n" +
	"\x05notch\x18\f \x01(\x01R\x05notch\x12;\n" +
	"\x1adimensions_for_detailing_n\x18\r \x01(\x01R\x17dimensionsForDetailingN\x123\n" +
	"\x16surface_area_per_metre\x18\x0e \x01(\x01R\x13surfaceAreaPerMetre\x123\n" +
	"\x16surface_area_per_tonne\x18\x0f \x01(\x01R\x13surfaceAreaPerTonne\x12=\n" +
	"\x1csecond_moment_of_area_axis_y\x18\x10 \x01(\x01R\x17secondMomentOfAreaAxisY\x12=\n" +
	"\x1csecond_moment_of_area_axis_z\x18\x11 \x01(\x01R\x17secondMomentOfAreaAxisZ\x128\n" +
	"\x19radius_of_gyration_axis_y\x18\x12 \x01(\x01R\x15radiusOfGyrationAxisY\x128\n" +
	"\x19radius_of_gyration_axis_z\x18\x13 \x01(\x01R\x15radiusOfGyrationAxisZ\x123\n" +
	"\x16elastic_modulus_axis_y\x18\x14 \x01(\x01R\x13elasticModulusAxisY\x123\n" +
	"\x16elastic_modulus_axis_z\x18\x15 \x01(\x01R\x13elasticModulusAxisZ\x123\n" +
	"\x16plastic_modulus_axis_y\x18\x16 \x01(\x01R\x13plasticModulusAxisY\x123\n" +
	"\x16plastic_modulus_axis_z\x18\x17 \x01(\x01R\x13plasticModulusAxisZ\x12-\n" +
	"\x12buckling_parameter\x18\x18 \x01(\x01R\x11bucklingParameter\x12'\n" +
	"\x0ftorsional_index\x18\x19 \x01(\x01R\x0etorsionalIndex\x12)\n" +
	"\x10warping_constant\x18\x1a \x01(\x01R\x0fwarpingConstant\x12-\n" +
	"\x12torsional_constant\x18\x1b \x01(\x01R\x11torsionalConstant\x12&\n" +
	"\x0farea_of_section\x18\x1c \x01(\x01R\rareaOfSection\"\x11\n" +
	"\x0fGetBeamsRequest\">\n" +
	"\x10GetBeamsResponse\x12*\n" +
	"\x05beams\x18\x01 \x03(\v2\x14.steelbeam.SteelBeamR\x05beams\"A\n" +
	"\x0eGetBeamRequest\x12/\n" +
	"\x13section_designation\x18\x01 \x01(\tR\x12sectionDesignation\"Q\n" +
	"\x0fGetBeamResponse\x12(\n" +
	"\x04beam\x18\x01 \x01(\v2\x14.steelbeam.SteelBeamR\x04beam\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"=\n" +
	"\x11CreateBeamRequest\x12(\n" +
	"\x04beam\x18\x01 \x01(\v2\x14.steelbeam.SteelBeamR\x04beam\"r\n" +
	"\x12CreateBeamResponse\x12(\n" +
	"\x04beam\x18\x01 \x01(\v2\x14.steelbeam.SteelBeamR\x04beam\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"R\n" +
	"\x15GetStockStatusRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bpostcode\x18\x02 \x01(\tR\bpostcode\"\x9f\x01\n" +
	"\x16GetStockStatusResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bpostcode\x18\x02 \x01(\tR\bpostcode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage2\xbb\x02\n" +
	"\x10SteelBeamService\x12C\n" +
	"\bGetBeams\x12\x1a.steelbeam.GetBeamsRequest\x1a\x1b.steelbeam.GetBeamsResponse\x12@\n" +
	"\aGetBeam\x12\x19.steelbeam.GetBeamRequest\x1a\x1a.steelbeam.GetBeamResponse\x12I\n" +
	"\n" +
	"CreateBeam\x12\x1c.steelbeam.CreateBeamRequest\x1a\x1d.steelbeam.CreateBeamResponse\x12U\n" +
	"\x0eGetStockStatus\x12 .steelbeam.GetStockStatusRequest\x1a!.steelbeam.GetStockStatusResponseB%Z#formandfunction-api/proto/steelbeamb\x06proto3"

var (
	file_proto_steelbeam_proto_rawDescOnce sync.Once
	file_proto_steelbeam_proto_rawDescData []byte
)

func file_proto_steelbeam_proto_rawDescGZIP() []byte {
	file_proto_steelbeam_proto_rawDescOnce.Do(func() {
		file_proto_steelbeam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_steelbeam_proto_rawDesc), len(file_proto_steelbeam_proto_rawDesc)))
	})
	return file_proto_steelbeam_proto_rawDescData
}

var file_proto_steelbeam_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_steelbeam_proto_goTypes = []any{
	(*SteelBeam)(nil),              // 0: steelbeam.SteelBeam
	(*GetBeamsRequest)(nil),        // 1: steelbeam.GetBeamsRequest
	(*GetBeamsResponse)(nil),       // 2: steelbeam.GetBeamsResponse
	(*GetBeamRequest)(nil),         // 3: steelbeam.GetBeamRequest
	(*GetBeamResponse)(nil),        // 4: steelbeam.GetBeamResponse
	(*CreateBeamRequest)(nil),      // 5: steelbeam.CreateBeamRequest
	(*CreateBeamResponse)(nil),     // 6: steelbeam.CreateBeamResponse
	(*GetStockStatusRequest)(nil),  // 7: steelbeam.GetStockStatusRequest
	(*GetStockStatusResponse)(nil), // 8: steelbeam.GetStockStatusResponse
}
var file_proto_steelbeam_proto_depIdxs = []int32{
	0, // 0: steelbeam.GetBeamsResponse.beams:type_name -> steelbeam.SteelBeam
	0, // 1: steelbeam.GetBeamResponse.beam:type_name -> steelbeam.SteelBeam
	0, // 2: steelbeam.CreateBeamRequest.beam:type_name -> steelbeam.SteelBeam
	0, // 3: steelbeam.CreateBeamResponse.beam:type_name -> steelbeam.SteelBeam
	1, // 4: steelbeam.SteelBeamService.GetBeams:input_type -> steelbeam.GetBeamsRequest
	3, // 5: steelbeam.SteelBeamService.GetBeam:input_type -> steelbeam.GetBeamRequest
	5, // 6: steelbeam.SteelBeamService.CreateBeam:input_type -> steelbeam.CreateBeamRequest
	7, // 7: steelbeam.SteelBeamService.GetStockStatus:input_type -> steelbeam.GetStockStatusRequest
	2, // 8: steelbeam.SteelBeamService.GetBeams:output_type -> steelbeam.GetBeamsResponse
	4, // 9: steelbeam.SteelBeamService.GetBeam:output_type -> steelbeam.GetBeamResponse
	6, // 10: steelbeam.SteelBeamService.CreateBeam:output_type -> steelbeam.CreateBeamResponse
	8, // 11: steelbeam.SteelBeamService.GetStockStatus:output_type -> steelbeam.GetStockStatusResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_steelbeam_proto_init() }
func file_proto_steelbeam_proto_init() {
	if File_proto_steelbeam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_steelbeam_proto_rawDesc), len(file_proto_steelbeam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_steelbeam_proto_goTypes,
		DependencyIndexes: file_proto_steelbeam_proto_depIdxs,
		MessageInfos:      file_proto_steelbeam_proto_msgTypes,
	}.Build()
	File_proto_steelbeam_proto = out.File
	file_proto_steelbeam_proto_goTypes = nil
	file_proto_steelbeam_proto_depIdxs = nil
}
